#!/usr/bin/env node
var program = require( 'commander' );
var myToolAuth = require('./mytoolAuth');

program
.option( '-e, --email [email]' )
.option( '-p, --password [password]' )
.parse( process.argv );

if( !program.email || !program.password ){
	console.error("required inputs missing");
	process.exit(1);
}

console.log("Login data to be stored in ", myToolAuth.authFilePath );

myToolAuth.login( { email: program.email, password: program.password } )
.then( function( authData ){
	console.log("Logged in as " + program.email );
})
.catch( function( error ){
	console.error("Failed to login as " + program.email);
	console.error( error );
	process.exit(1);
});