#!/usr/bin/env node
var myToolAuth = require('./mytoolAuth');
myToolAuth.isAuthenticated()
.then( function( authData ){
	if( authData.email ){
		console.log( authData.email );
		process.exit(0);
	}else{
		console.log( "Not logged in. Use mytool-login");
		process.exit(1);
	}
});